### ISSUE TITLE
Adapt default viewport to reduce FID

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-toolbox-php#126]
If the `viewport` tag does not contain any scale and only has `width=device-width`, double-tap to zoom is disable, which means the browser does not need to add an artificial delay of 300ms or more to detect a double-tap.

This improves FID.

See https://github.com/ampproject/amp.dev/pull/5063

**Comment by schlessera** [comment]
The viewport is not currently being added or adapted by the optimizer, and that should probably stay that way. The viewport is best adapted in the "Sanitizer" that is yet to be transferred into the library. The meta tag sanitizer in the `amp-wp` package already does the above, so I'm closing this again for now.

**Comment by westonruter** [comment]
IMO, this to me seems appropriate for an optimizer transformer, at least in the current implementation in AMP plugin's sanitizer: it just strips out the `initial-scale=1.0` because it apparently fixes FID and it makes no difference to the appearance of the page as far as we could tell, since it seems that is the default value anyway. 

But, the Chromium bugfix is in progress, so this may be irrelevant in the long run: https://bugs.chromium.org/p/chromium/issues/detail?id=1108987
