### ISSUE TITLE
Amp not valid

### ISSUE THREAD

**Issue by spinmar** [ampproject/amp-toolbox-php#252]
Hi,
I'm trying to introduce amp-toolbox in our pipiline to optimize the code.
I'm passing an amp string document to TransformationEngine (default configuration) and I'm getting as result an other amp document which is not valid.
My code is:

```php
$transformationEngine = new TransformationEngine();    
$errorCollection      = new ErrorCollection;           
$back = $view->getContent();
		
		$optimizedHtml = $transformationEngine->optimizeHtml(  
				$view->getContent(),                                  
				$errorCollection                                   
		);
.....
```

$view->getContent() is a valid amp string while $optimizedHtml  is not valid. The transformationEngine moves my meta tags in the head section of $view->getContent() in the body section in optimizedHtml  and the result is not a valid amp string.

Am I missing something?

Thanks

**Comment by schlessera** [comment]
Can you provide a short HTML snippet from your content (abbreviated to just what is needed) to replicate this behavior? Or do you have a link to an AMP page that fails like this?

**Comment by spinmar** [comment]
Sure.
The source amp page (input to transformationEngine) is this one:

[https://sport.virgilio.it/morata-buffon-bentancur-quante-spine-nelle-zampe-delle-zebre-682466/amp/](url)

It is a valid amp page. We would like to introduce the amp optimizer (amp-toolbox) but we are experimenting the error above.
Thanks

**Comment by spinmar** [comment]
Same problem if I try to use optimizeDom:
Ex.
`
$dom    = Document::fromHtml($view->getContent());
$transformationEngine = new TransformationEngine();  
$errorCollection      = new ErrorCollection; 
$output;
$transformationEngine->optimizeDom($dom, $errorCollection);
if ($errorCollection->count() > 0) {
    $output =  $view->getContent();
}
else {
    $output =  $dom->saveHTML();
}
....
`
What am I missing?

**Comment by schlessera** [comment]
@spinmar I found the problem. You are adding two extension scripts that are unused. Even though this is not a problem for valid AMP, it is flagged as a validation issue on optimized AMP.

The two extension scripts that the validator detects as unused are for `amp-instagram` and `amp-twitter`. If you remove these extension scripts from your source AMP file, the optimized AMP file should be valid as well.

Note that we are working on a transformer that takes care of adding and pruning these extension scripts automatically, but it has not yet been released: https://github.com/ampproject/amp-toolbox-php/pull/210

I'm closing this issue, as I don't think the problem lies with the Optimizer. Feel free to reopen if you think I missed something.
