### ISSUE TITLE
Bug: Inconsistent double-encoding of already encoded HTML entities

### ISSUE THREAD

**Issue by AaronMLB** [ampproject/amp-toolbox-php#409]
I've just started trying out the AMP Optimizer but am experiencing some very odd, inconsistent encoding behaviour.

Specifically, my textual strings have all already been passed through `htmlentities($string, ENT_COMPAT | ENT_HTML5, 'UTF-8', false);`, and so are pre-encoded; the Optimizer is then doing this again _but not all of the time_.

For example, on the first page I've tried, I get some characters correctly showing up in the browser (`&` from `&amp;`), but also immediately below, `&colon;` is rendered, and sure enough on viewing the page source it has become `&amp;colon;`.

Is the Optimizer invoking a custom `htmlentities()` equivalent that does not include all of the entities that PHP encodes (at least under UTF-8)?

Other affected entities I've spotted just on the one page include `&excl;`, `&comma;` and `&quest;`, so not rare characters even in English!

**Comment by schlessera** [comment]
@AaronMLB To be able to properly diagnose this, we'd need access to the content that is breaking. Are you able to provide us with both the unoptimized and the optimized HTML of a page that breaks for you?

**Comment by AaronMLB** [comment]
Of course. Find files in this repo: https://github.com/AaronMLB/amp-optimizer-encoding

The original real source page is https://www.comedy.co.uk/

I also now note that the optimizer is stripping media queries on `amp-ad` unites such as `media="only screen and (max-width: 767px)"`, which are used to target different sized adverts to different devices.

**Comment by schlessera** [comment]
@ediamin I tested this with a very basic test, and indeed, HTML entities are encoded twice, resulting in things like `&comma;` => `&amp;comma;`. A first scan did not reveal any use of `htmlentities()` or `htmlspecialchars()` that would cause this.

Can you do some investigating into the root cause of this. Maybe this is a `libxml` setting we're missing or similar.

**Comment by ediamin** [comment]
@schlessera from my test, I've found that the encoding is done by the DOMDocument::saveHTML method, but couldn't find any good solution or option to ignore this. Some people suggested to set `$doc->substituteEntities = false` to ignore the encoding, but in my tests it had no effect. Also couldn't find any proper libxml related option for this. Do you have any suggestions on what I should look for?

**Comment by schlessera** [comment]
@ediamin The first thing I'd explore is to use https://www.php.net/manual/en/function.html-entity-decode.php to convert all included HTML entities into their actual characters.

**Comment by ediamin** [comment]
@schlessera `html_entity_decode( $encoded, ENT_HTML5 );` works perfectly. It converts the `&excl;`, `&comma;` `&quest;` and other entities back to their actual characters. So, should we only decode them in a BeforeLoadFilter? In that case the `Document` will produce html with actual characters, not entities. We cannot use `htmlentities` in a `AfterSaveFilter`, because that will break other special characters like angle brackets for html tags. With that in mind, isn't it better to decode the source before consume the `Document` instead of having it in a filter?
