### ISSUE TITLE
Adapt PreloadHeroImages to support new OptimizeHeroImage configuration arguments

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-toolbox-php#55]
The Node.JS implementation deprecated `PreloadHeroImages` in favor of a new `OptimizeHeroImages` with more sophisticated configuration arguments.

The PHP version needs to be adapted in order to support these via the imported spec tests.

See https://github.com/ampproject/amp-toolbox/pull/1133

**Comment by westonruter** [comment]
This will also involve discontinuing the preloading of images per https://github.com/ampproject/amp-toolbox/pull/1132, yes?

**Comment by westonruter** [comment]
Importantly, there is now a `maxHeroImageCount` parameter to override the default max of 2: https://github.com/ampproject/amphtml/issues/30442#issuecomment-818081574.

**Comment by westonruter** [comment]
In the context of the AMP plugin's `DetermineHeroImages` transformer, we should remove any limit for hero images that are located in the header. Basically, we should do SSR for every image that has `data-hero` or `data-hero-candidate`. The limit should only apply to automatic detection.

**Comment by westonruter** [comment]
This specifically will help the case identified on a [support forum topic](https://wordpress.org/support/topic/fid-lcp-and-cls-issue/):

![image](https://user-images.githubusercontent.com/134745/116732479-b5cdf500-a99f-11eb-8ece-558413e3a8cd.png)

The LCP image here is following 2 previous images that were identified as heroes. Nevertheless, this LCP image _is_ a featured image and it has `data-hero-candidate`. But because there were 2 preceding images, it was not made a `data-hero`. But since this image had `loading=lazy` it would be safe to go ahead and prerender even though there are 2 previous images prerendered.

**Comment by westonruter** [comment]
I'd love to get this into AMP plugin v2.1.3. For the immediate term, I think we can just omit any image that has `data-hero-candidate` from counting against the `DATA_HERO_MAX`.

**Comment by schlessera** [comment]
> But since this image had loading=lazy it would be safe to go ahead and prerender even though there are 2 previous images pre-rendered.

Note that we currently strip the `loading=lazy` attribute from hero images specifically to improve the LCP. If we'd take this into account as hero image as well, we'd also strip the lazy-loading, making it again less safe.

**Comment by westonruter** [comment]
> Note that we currently strip the `loading=lazy` attribute from hero images specifically to improve the LCP. If we'd take this into account as hero image as well, we'd also strip the lazy-loading, making it again less safe.

Do we? As of #149 we persist the `loading=lazy` which was on the `noscript > img` fallback.

**Comment by westonruter** [comment]
In other words, if an `img` originally had `loading=lazy`, then this will be preserved. In this way, we maintain whatever WordPress core or the theme had decided was a hero.
